import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-muted`}
      >
        <main className="h-full">
          {children}
        </main>
        <footer className="block h-20 bottom-0">
          <div className="bg-black h-full flex items-center justify-center">
            <h1 className="text-white">© 2025 Dara. All rights reserved.</h1>
          </div>
        </footer>
      </body>
    </html>
  );
}
